tests/cluster: hold the LXD snap from the source channel
Before this commit, one CI run failed with:

```
==> Upgrading the cluster
++ seq 3
+ for i in $(seq "${SIZE}")
+ lxc exec m1 -- snap wait system seed.loaded
+ lxc exec m1 -- snap refresh
2025-06-10T08:26:55Z INFO Waiting for "snap.lxd.daemon.service" to stop.
lxd 6.4-2336111 from Canonical** refreshed
+ lxc exec m1 -- snap changes
ID   Status  Spawn               Ready               Summary
1    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize system state
2    Done    today at 08:25 UTC  today at 08:25 UTC  Install "lxd" snap from "latest/stable" channel
3    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize device
4    Done    today at 08:26 UTC  today at 08:27 UTC  Refresh "lxd" snap

+ lxc exec m1 -- snap switch lxd --channel=latest/edge --cohort=+
"lxd" switched to the "latest/edge" channel and the "+" cohort

+ '[' 1 = 3 ']'
+ for i in $(seq "${SIZE}")
+ lxc exec m2 -- snap wait system seed.loaded
+ lxc exec m2 -- snap refresh
All snaps up to date.
+ lxc exec m2 -- snap changes
ID   Status  Spawn               Ready               Summary
1    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize system state
2    Done    today at 08:25 UTC  today at 08:25 UTC  Install "lxd" snap from "latest/stable" channel
3    Done    today at 08:25 UTC  today at 08:25 UTC  Initialize device
4    Doing   today at 08:27 UTC  -                   Refresh "lxd" snap from "+" cohort
5    Done    today at 08:27 UTC  today at 08:27 UTC  Refresh all snaps: no updates

+ lxc exec m2 -- snap switch lxd --channel=latest/edge --cohort=+
error: snap "lxd" has "refresh-snap" change in progress
+ cleanup
```

At the time of the problem, `latest/stable` had a new revision phasing in.
Since we intentionally do not use `--cohort=+` for installing the source
version, the `snap refresh` that ran on `m1` caused an early cluster-wide
refresh of the LXD snap as we can see on `m2` where the `snap switch lxd`
command failed due to the LXD snap having changes in progress (due to the
"please refresh" notification received from `m1`).

While we expect a cluster-wide refresh to occur, it must happen later on in the script
when the last member (`i` and `SIZE` equal 3, so `m3`) triggers it:

```
echo "==> Upgrading the cluster"
for i in $(seq "${SIZE}"); do
    lxc exec "m${i}" -- snap wait system seed.loaded
    lxc exec "m${i}" -- snap refresh
    # XXX: there should be no refresh ongoing but we've seen races before so let's collect evidences
    lxc exec "m${i}" -- snap changes
    lxc exec "m${i}" -- snap switch lxd --channel="$3" --cohort=+
    if [ "$i" = "${SIZE}" ]; then
        lxc exec "m${i}" -- timeout 10m snap refresh lxd
    fi
done
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>