github: reclaim disk to avoid issue with kernel 6.5.0-1025-azure
With this kernel the ephemeral device remains active when microceph tries to wipe it:

```
jbd2/sdb1  537                           root  cwd       DIR                8,1          4096          2 /
jbd2/sdb1  537                           root  rtd       DIR                8,1          4096          2 /
jbd2/sdb1  537                           root  txt   unknown                                             /proc/537/exe
```

`microceph`'s error signature looks like this:

```
+ sudo microceph disk add --wipe /dev/sdb

+----------+---------+
|   PATH   | STATUS  |
+----------+---------+
| /dev/sdb | Failure |
+----------+---------+
Error: failed to bootstrap OSD: Failed to run: ceph-osd --mkfs --no-mon-config -i 1: exit status 250 (2024-10-11T18:58:48.321+0000 7f5652ac1600 -1 bluestore(/var/lib/ceph/osd/ceph-1/block) _read_bdev_label unable to decode label /var/lib/ceph/osd/ceph-1/block at offset 102: void bluestore_bdev_label_t::decode(ceph::buffer::v15_2_0::list::const_iterator&) decode past end of struct encoding: Malformed input [buffer:3]
2024-10-11T18:58:48.325+0000 7f5652ac1600 -1 bluestore(/var/lib/ceph/osd/ceph-1/block) _read_bdev_label unable to decode label /var/lib/ceph/osd/ceph-1/block at offset 102: void bluestore_bdev_label_t::decode(ceph::buffer::v15_2_0::list::const_iterator&) decode past end of struct encoding: Malformed input [buffer:3]
2024-10-11T18:58:48.325+0000 7f5652ac1600 -1 bluestore(/var/lib/ceph/osd/ceph-1/block) _read_bdev_label unable to decode label /var/lib/ceph/osd/ceph-1/block at offset 102: void bluestore_bdev_label_t::decode(ceph::buffer::v15_2_0::list::const_iterator&) decode past end of struct encoding: Malformed input [buffer:3]
2024-10-11T18:58:48.345+0000 7f5652ac1600 -1 bdev(0x55573ad72000 /var/lib/ceph/osd/ceph-1/block) open open got: (16) Device or resource busy
2024-10-11T18:58:48.345+0000 7f5652ac1600 -1 bluestore(/var/lib/ceph/osd/ceph-1) mkfs failed, (16) Device or resource busy
dmesg logs
```

Hypothesys: when `/mnt` is umount'ed, it's not done doing the lazy init which
causes the jbd2 thread to stick around preventing the release of the partition?

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>